server:
  port: ${PORT:8080}
  error:
    include-message: always

spring:
  application:
    name: pokemon-api
  profiles:
    active: default

  #POKE-API
poke:
  api:
    endpoint: https://pokeapi.co/api/v2/pokemon/